### DISCUSSION TITLE
Enable SSL with the Spark sever

### DISCUSSION THREAD

**Discussion by Boogy1** [FirelyTeam/spark#538] [Q&A]
I'm Trying to enable internally in docker network ssl.
Spark Documentation says that i have to adjust environment parameters: 
![image](https://user-images.githubusercontent.com/122994812/213203138-a259218e-62b0-4405-af22-ea46653a0c8a.png)

But actually i don't know the correct syntax for it in the docker file. 
Is it the same schema like VONK_<setting_level_1>[:<setting_level_n>]* or is it for this Spark without "VONK_" prefix?

**Comment by kennethmyhra** [comment]
I'll admit to not being a docker expert, I had someone else set this up for me. The below docker file is the one we use for our test servers which you can probably modify.

```
version: "3"
services:

  proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    depends_on:
      - spark-r4
      - spark-stu3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d:ro
      - /etc/nginx/certs:/etc/nginx/certs:ro
      - /usr/share/nginx/html:/usr/share/nginx/html:rw
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"

  proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - proxy
    container_name: nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/nginx/certs:/etc/nginx/certs:rw
      - /usr/share/nginx/html:/usr/share/nginx/html:rw
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d:rw

  spark-r4:
    container_name: spark-r4
    restart: always
    image: sparkfhir/spark:r4-latest
    depends_on:
      - mongodb
    environment:
      - VIRTUAL_HOST=spark.example.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=spark.example.com
      - LETSENCRYPT_EMAIL=post@example.com
      - StoreSettings__ConnectionString=mongodb://mongodb:27017/spark-r4
      - SparkSettings__Endpoint=https://spark.example.com/fhir
    volumes:
      - /var/www/spark-r4/database.db:/app/database.db

  spark-stu3:
    container_name: spark-stu3
    restart: always
    image: sparkfhir/spark:stu3-latest
    depends_on:
      - mongodb
    environment:
      - VIRTUAL_HOST=spark-stu3.example.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=spark-stu3.example.com
      - LETSENCRYPT_EMAIL=post@example.com
      - StoreSettings__ConnectionString=mongodb://mongodb:27017/spark-stu3
      - SparkSettings__Endpoint=https://spark-stu3.example.com/fhir
    volumes:
      - /var/www/spark-stu3/database.db:/app/database.db

  mongodb:
    container_name: mongodb
    restart: always
    image: mongo
    ports:
      - "17017:27017"
    volumes:
      - /var/lib/mongodb:/data/db
```
