### ISSUE TITLE
Multiple FHIR Stores, like GCP has

### ISSUE THREAD

**Issue by wowkin2** [FirelyTeam/spark#483]
When I work with GCP I use multiple [GCP FHIR data stores](https://cloud.google.com/healthcare-api/docs/concepts/fhir#fhir_architecture) to separate data from different clients.

Does Spark support anything similar?
Or is there a way to have multiple database with prefix in URL:
[http://spark-fhir:80/prefix/fhir](http://spark-fhir:80/prefix/fhir)

**Comment by kennethmyhra** [comment]
Nothing out of the box. So probably the best approach is as you outline to set up multiple instances of the server on different prefixes.

**Comment by wowkin2** [comment]
In a `docker-compose.yml` I [found here an example](https://github.com/FirelyTeam/spark/blob/r4/master/.docker/docker-compose.example.yml#L8) which should allow to set:
```
StoreSettings__ConnectionString=mongodb://root:CosmicTopSecret@mongodb:27017/prefix-spark?authSource=admin
SparkSettings__Endpoint=http://localhost:5555/prefix/fhir
```
But looks like it is not working. Not for spark URL, nor mongodb database.

**Comment by wowkin2** [comment]
@kennethmyhra can you help me with that?

**Comment by kennethmyhra** [comment]
I can give you an example of the docker-compose.yml we use for our test servers:
- https://spark.incendi.no
- https://spark-stu3.incendi.no

The prefix is then in the host name part, and the database name is suffixed. The database will be created automatically by Spark if it does not exist so just start by POSTing a few examples to your server.

```
version: "3"
services:

  proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    depends_on:
      - spark-r4
      - spark-stu3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d:ro
      - /etc/nginx/certs:/etc/nginx/certs:ro
      - /usr/share/nginx/html:/usr/share/nginx/html:rw
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"

  proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - proxy
    container_name: nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/nginx/certs:/etc/nginx/certs:rw
      - /usr/share/nginx/html:/usr/share/nginx/html:rw
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d:rw

  spark-r4:
    container_name: spark-r4
    restart: always
    image: sparkfhir/spark:r4-latest
    depends_on:
      - mongodb
    environment:
      - VIRTUAL_HOST=spark.example.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=spark.example.com
      - LETSENCRYPT_EMAIL=post@example.com
      - StoreSettings__ConnectionString=mongodb://mongodb:27017/spark-r4
      - SparkSettings__Endpoint=https://spark.example.com/fhir
    volumes:
      - /var/www/spark-r4/database.db:/app/database.db

  spark-stu3:
    container_name: spark-stu3
    restart: always
    image: sparkfhir/spark:stu3-latest
    depends_on:
      - mongodb
    environment:
      - VIRTUAL_HOST=spark-stu3.example.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=spark-stu3.example.com
      - LETSENCRYPT_EMAIL=post@example.com
      - StoreSettings__ConnectionString=mongodb://mongodb:27017/spark-stu3
      - SparkSettings__Endpoint=https://spark-stu3.example.com/fhir
    volumes:
      - /var/www/spark-stu3/database.db:/app/database.db

  mongodb:
    container_name: mongodb
    restart: always
    image: mongo
    ports:
      - "17017:27017"
    volumes:
      - /var/lib/mongodb:/data/db
```
