### ISSUE TITLE
Fahrenheit cannot be converted to base units

### ISSUE THREAD

**Issue by JoogsWasTaken** [FirelyTeam/spark#501]
**Describe the bug**
When using Fahrenheit as a unit for a value, Spark cannot convert the value to its corresponding base unit.

**To Reproduce**
Linked to this issue are FHIR bundles, generated by [Synthea](https://github.com/synthetichealth/synthea), that set up [hospital](https://github.com/FirelyTeam/spark/files/9349205/hospitalInformation1660206653416.txt) and [practitioner](https://github.com/FirelyTeam/spark/files/9349213/practitionerInformation1660206653416.txt) resources, to then insert a [patient with an observation resource](https://github.com/FirelyTeam/spark/files/9349219/testquant.txt) that has a value attached to it. So:

1. Run Spark FHIR server on the latest version (1.5.13-r4)
2. POST the hospital bundle, then the practitioner bundle
3. POST the patient bundle

The server will then respond with a 500 and the following message:

```json
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "diagnostics": "InvalidCastException: Quantity could not be converted to base units"
        }
    ]
}
```

**Expected behavior**
The server should be able to process Fahrenheit.

**Spark version**
- Version: 1.5.13-r4

**Operating system + Database**
- OS: Arch Linux with LTS Kernel 5.15.60-1

**Container service / Cloud infrastructure:**
- Container service: `sparkfhir/spark:v1.5.13-r4`
- Database container service: `sparkfhir/mongo:v1.5.13-r4`

This is the Compose file that I use:

```yml
version: "3.9"

services:

  spark:
    image: sparkfhir/spark:v1.5.13-r4
    environment:
      - StoreSettings__ConnectionString=mongodb://root:CosmicTopSecret@mongo:27017/spark?authSource=admin
      - SparkSettings__Endpoint=http://localhost:8080/fhir
    ports:
      - "8080:80"
  
  mongo:
    image: sparkfhir/mongo:v1.5.13-r4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=CosmicTopSecret
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
```
  
**Additional context**
This is an issue that I haven't encountered with other open-source FHIR servers. Therefore I think this is worth looking into to get consistent results across implementations.

It's also worth noting that changing the value to an integer (e.g. 102) changes nothing about this behavior. Changing the unit to Celsius, so setting both `unit` and `code` in the `valueQuantity` object to `[degC]`, works. So this is an issue that, by my little bits of research, only affects Fahrenheit.
